### PR TITLE
[asset_pricing_lph] Adjustments for new lecture

### PR DESCRIPTION
**Pull request by mmcky**
This PR adjust `asset_pricing_lph` to:

1. move `display math` to be on own lines following `$$`
2. moves figure from `lecture` to `_static/lecture_specific/asset_pricing_lph/`
3. remove accidental `z` from header

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude it doesn't seem to have any issues when using 

http://www.tlhiv.org/ltxpreview/

and I can't see any special unicode etc.

**Comment by AakashGfude** [comment]
> @AakashGfude it doesn't seem to have any issues when using
> 
> http://www.tlhiv.org/ltxpreview/
> 
> and I can't see any special unicode etc.

Yeah, i also didn't have any issues in overleaf. But it seems the `\\` in maths was throwing it off for jb.

**Comment by mmcky** [comment]
thanks @AakashGfude maybe we should use this equation as a test case and dig into why `jb` always trips up on this. 

Appreciate the help.

**Comment by AakashGfude** [comment]
> thanks @AakashGfude maybe we should use this equation as a test case and dig into why `jb` always trips up on this.
> 
> Appreciate the help.

@mmcky So, should we merge this in the interim?

**Comment by mmcky** [comment]
thanks @AakashGfude I just want to show @thomassargent30 the differences and then we can merge.

**Pull request merged**
