### PR TITLE
ENH: Upgrade to jupyter-book==0.15.1 + associated packages

### PR DESCRIPTION
**Pull request by mmcky**
This PR upgrades to `jupyter-book==0.15.1` + associated packages

### CODE REVIEW

**Comment by mmcky** [comment]
**Link Checker:**

- [ ] ( tax_smoothing_1: line  408) broken    https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/lqcontrol.py#L334 - Anchor 'L334' not found
- [ ] (     zreferences: line   13) broken    https://doi.org/10.3982/ECTA8070 - 403 Client Error: Forbidden for url: https://onlinelibrary.wiley.com/resolve/doi?DOI=10.3982/ECTA8070
- [ ] (     zreferences: line   13) broken    https://doi.org/10.1086/262078 - 403 Client Error: Forbidden for url: https://www.journals.uchicago.edu/doi/10.1086/262078
[218](https://github.com/QuantEcon/lecture-python-advanced.myst/actions/runs/4485712457/jobs/7887514330?pr=129#step:5:219)
- [ ] (     zreferences: line   13) broken    https://doi.org/10.1086/261749 - 403 Client Error: Forbidden for url: https://www.journals.uchicago.edu/doi/10.1086/261749

**Comment by mmcky** [comment]
Other Issues:

- [ ] /home/runner/work/lecture-python-advanced.myst/lecture-python-advanced.myst/lectures/five_preferences.md:238: WARNING: Deprecated `cell_metadata_key` 'render' found, replace with 'mystnb' [myst.cell_metadata_key]

**Comment by mmcky** [comment]
- [ ] /home/runner/work/lecture-python-advanced.myst/lecture-python-advanced.myst/lectures/knowing_forecasts_of_others.md:922: WARNING: No mime type available in priority list for builder 'linkcheck' ('text/html') [mystnb.mime_priority]

**Comment by mmcky** [comment]
- [ ] @HumphreyYang would you be able to organise someone to review `knowing_forecasts_of_others` and fix links like the following with `cite` roles

  [[Kas00](https://python-advanced.quantecon.org/zreferences.html#id24)]

**Comment by HumphreyYang** [comment]
> * [ ]  @HumphreyYang would you be able to organise someone to review `knowing_forecasts_of_others` and fix links like the following with `cite` roles
>   ```lisp
>   [[Kas00](https://python-advanced.quantecon.org/zreferences.html#id24)]
>   ```

Thanks @mmcky, I will do it :)

**Comment by mmcky** [comment]
thanks @HumphreyYang for your fixes to the references. 

I will merge this now.

**Pull request merged**
