### PR TITLE
TMP: install numba < 0.60 to see if amss is fixed

### PR DESCRIPTION
**Pull request by mmcky**
See if fix in #163 works

### CODE REVIEW

**Comment by kp992** [comment]
@mmcky Let's pin this to `numba=0.59.1` because of https://github.com/QuantEcon/lecture-python-advanced.myst/issues/163#issuecomment-2197889033.

**Comment by kp992** [comment]
@mmcky Thanks. Does the CI usually take this long for Latex?

**Comment by kp992** [comment]
This is working fine: https://github.com/QuantEcon/lecture-python-advanced.myst/actions/runs/9721377407/job/26833965195 with numba-0.59.1. Thanks @mmcky.

**Comment by mmcky** [comment]
> @mmcky Thanks. Does the CI usually take this long for Latex?

Due to software environment changes, I think it is executing ALL lectures. Some of the ones in this collection take a very long time to run.

**Pull request merged**
