### PR TITLE
Fix ValueError in opt_tax_recur.md and amss Lectures

### LINKED ISSUE #144: Execution Error in opt_tax_recur.md and amss Lectures
There is a reported execution error in `opt_tax_recur.md`

in this cell

```python
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
π = np.array([[0, 1, 0,   0,   0,  0],
              [0, 0, 1,   0,   0,  0],
              [0, 0, 0, 0.5, 0.5,  0],
              [0, 0, 0,   0,   0,  1],
              [0, 0, 0,   0,   0,  1],
              [0, 0, 0,   0,   0,  1]])

g = np.array([0.1, 0.1, 0.1, 0.2, 0.1, 0.1])
crra_pref = CRRAutility()

# Solve sequential problem
seq = SequentialLS(crra_pref, π=π, g=g)
sHist_h = np.array([0, 1, 2, 3, 5, 5, 5])
sHist_l = np.array([0, 1, 2, 4, 5, 5, 5])
sim_seq_h = seq.simulate(1, 0, 7, sHist_h)
sim_seq_l = seq.simulate(1, 0, 7, sHist_l)

fig, axes = plt.subplots(3, 2, figsize=(14, 10))
titles = ['Consumption', 'Labor Supply', 'Government Debt',
          'Tax Rate', 'Government Spending', 'Output']

for ax, title, sim_l, sim_h in zip(axes.flatten(),
                                   titles,
                                   sim_seq_l[:6],
                                   sim_seq_h[:6]):
    ax.set(title=title)
    ax.plot(sim_l, '-ok', sim_h, '-or', alpha=0.7)
    ax.grid()

plt.tight_layout()
plt.show()
------------------
```

results in 

```
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.
```

### PR DESCRIPTION
**Pull request by HumphreyYang**
This PR resolves #144.

### CODE REVIEW

**Comment by HumphreyYang** [comment]
Hi Matt, 

This PR fixes the ValueErrors under the new `anaconda` version. I merged your branch to this one to validate the build. Please feel free to merge your PR before mine.

Note that there are runtime warnings in `amss3`, which exists way back to 2020. I will keep my hands off this warning for now as it might be intentional, but I will create an issue on this.

Many thanks in advance.

**Comment by HumphreyYang** [comment]
Hi @mmcky 

The CI still gives me 


```
Error: no downloadable artifacts found (expired)
```

when I put the download folder back. Could you please kindly let me know how to resolve this?

**Comment by mmcky** [comment]
> Hi @mmcky
> 
> The CI still gives me
> 
> ```
> Error: no downloadable artifacts found (expired)
> ```
> 
> when I put the download folder back. Could you please kindly let me know how to resolve this?

Fixing that right as we speak. The Cache is running now -- it had expired and I have now added a monthly run schedule

**Comment by mmcky** [comment]
@HumphreyYang we are caught in a catch 22. The cache doesn't want to upload the `build` folder without execution passing and this won't run without the cache being up to date. If there is a simple fix for that lecture -- let's merge it and get the cache to build.

**Comment by mmcky** [comment]
Let's open the PR to fix that one lecture causing the issue. I will then merge that and fix the cache build then we can update this PR from main. Does that sound OK?

**Pull request merged**
