### PR TITLE
ENH: Add link checker to GitHub Actions Workflow

### PR DESCRIPTION
**Pull request by mmcky**
This PR runs a link checker on:

1. schedule (daily),
2. on the creation or reopening of a PR (so only will run once)

### CODE REVIEW

**Comment by mmcky** [comment]
@HumphreyYang also this one if you have time would be great
[linkcheck-reports-3.zip](https://github.com/QuantEcon/lecture-python-advanced.myst/files/9502198/linkcheck-reports-3.zip)

**Comment by HumphreyYang** [comment]
Hi @mmcky,

I found several broken links are related to the reference and .bib file.

```
(knowing_forecasts_of_others: line 1576) broken    https://python-advanced.quantecon.org/zreferences.html#id26 - Anchor 'id26' not found
(knowing_forecasts_of_others: line 1576) broken    https://python-advanced.quantecon.org/zreferences.html#id27 - Anchor 'id27' not found
```

I found both of them in the .bib file but they are not present in the reference chapter (zreference.md). Could you please give me some hints on where the problems are? I have used the .bib checker to check related entries but they are recognised as correct entries.

Many thanks.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

I have updated all broken links. 

I noticed two things during the process:

1. The link checker will only show one line if there are multiple lines with the same broken link.
2. This lecture series used links to include references instead of `{cite}`. This causes some issue since several entries in the `.bib` file does not appear in the `zreference.md`.

Could you please kindly review my changes and merge them if they look good to you?

Many thanks.

**Comment by mmcky** [comment]
thanks @HumphreyYang that is good to know. 

The `cite` update is the way to go. Thanks!

**Pull request merged**
