### PR TITLE
Update asset_pricing_lph.md

### PR DESCRIPTION
**Pull request by sousaru**
Corrected equation 35.5 (eq:EMRS) by removing the extra E(m) dividing the standard-deviation.

### CODE REVIEW

**Comment by mmcky** [comment]
@shlff would you have time to review this updated equation?

**Comment by mmcky** [comment]
thanks @sousaru for your PR. Sorry it has taken me a while to loop back around to it.

**Comment by shlff** [comment]
Sure @mmcky. I will review this later today.

**Comment by shlff** [comment]
Thanks @sousaru .

Hi @mmcky , I've reviewed this PR, and I reckon it is a right correction:

given the definition of $\rho_{m, R^{i}}$

the equation (35.5) (https://python-advanced.quantecon.org/asset_pricing_lph.html#equation-eq-emr5) in the lecture should be

$$
1= E\left(m R^{i}\right)=E(m) E\left(R^{i}\right)+\rho_{m, R^{i}}\sigma(m) \sigma\left(R^{i}\right)
$$

since it is derived directly from equation (35.2) (https://python-advanced.quantecon.org/asset_pricing_lph.html#equation-eq-emr2).

**Comment by mmcky** [comment]
thanks @sousaru and @shlff -- we really appreciate your PR.

**Pull request merged**
