### PR TITLE
Calvo Machine Learning Lecture

### PR DESCRIPTION
**Pull request by mmcky**
This PR adds `calvo` machine learning lecture

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] fix compatibility with latex builder

**Comment by HumphreyYang** [comment]
Many thanks @mmcky,

I just pushed a very minor change on the printing of the decision rule.

**Comment by mmcky** [comment]
Thanks @thomassargent30 and @HumphreyYang. 

Merging this now then will tag a release.

**Comment by HumphreyYang** [comment]
Many thanks @mmcky, sorry for this but I wanted to push just one more small edit. 

I will make a new PR now and we can release it.

**Comment by mmcky** [comment]
Thanks @HumphreyYang that would be great. I will wait for any edits you have today.

**Pull request merged**
