### PR TITLE
Remove unused imports

### LINKED ISSUE #139: Files containing unused imports
```console
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/BCG_complete_mkts.py:870:1: F401 'pandas as pd' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/BCG_incomplete_mkts.py:707:1: F401 'pandas as pd' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/BCG_incomplete_mkts.py:709:1: F401 'scipy.stats.norm' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/BCG_incomplete_mkts.py:712:1: F401 'scipy.optimize.bisect' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/BCG_incomplete_mkts.py:1249:1: F401 'mpl_toolkits.mplot3d' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/additive_functionals.py:76:1: F401 'scipy as sp' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/amss.py:44:1: F401 'scipy.optimize.root' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/amss.py:45:1: F401 'interpolation.splines.eval_linear' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/amss.py:46:1: F401 'quantecon.optimize' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/amss.py:47:1: F401 'numba.njit' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/amss.py:47:1: F401 'numba.prange' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/amss.py:47:1: F401 'numba.float64' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/amss.py:48:1: F401 'numba.experimental.jitclass' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/arellano.py:83:1: F401 'random' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/arellano.py:85:1: F401 'numba.int64' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/arellano.py:85:1: F401 'numba.float64' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/arellano.py:86:1: F401 'numba.experimental.jitclass' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/asset_pricing_lph.py:584:1: F401 'scipy.stats.stats' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/asset_pricing_lph.py:586:1: F401 'statsmodels.sandbox.regression.gmm.GMM' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/black_litterman.py:90:1: F401 'scipy as sp' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/cattle_cycles.py:52:1: F401 'quantecon.LQ' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/chang_credible.py:88:1: F401 'quantecon as qe' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/chang_ramsey.py:77:1: F401 'quantecon as qe' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/five_preferences.py:61:1: F401 'matplotlib.cm' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/five_preferences.py:62:1: F401 'mpl_toolkits.mplot3d.Axes3D' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/five_preferences.py:66:1: F401 'matplotlib.colors.ListedColormap' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/five_preferences.py:66:1: F401 'matplotlib.colors.BoundaryNorm' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/growth_in_dles.py:55:1: F401 'quantecon.LQ' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/hs_invertibility_example.py:49:1: F401 'quantecon.LQ' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/irfs_in_hall_model.py:47:1: F401 'quantecon.LQ' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/knowing_forecasts_of_others.py:923:1: F401 'plotly.subplots.make_subplots' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/knowing_forecasts_of_others.py:925:1: F401 'plotly.express as px' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/lucas_asset_pricing_dles.py:57:1: F401 'quantecon.LQ' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/markov_jump_lq.py:255:1: F401 'mpl_toolkits.mplot3d.Axes3D' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/matsuyama.py:51:1: F401 'seaborn as sns' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/matsuyama.py:52:1: F401 'numba.vectorize' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/muth_kalman.py:45:1: F401 'scipy.linalg as la' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/muth_kalman.py:49:1: F401 'scipy.stats.norm' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/opt_tax_recur.py:73:1: F401 'scipy.optimize.root' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/opt_tax_recur.py:74:1: F401 'quantecon.MarkovChain' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/opt_tax_recur.py:75:1: F401 'quantecon.optimize.nelder_mead.nelder_mead' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/opt_tax_recur.py:76:1: F401 'interpolation.interp' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/opt_tax_recur.py:77:1: F401 'numba.njit' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/opt_tax_recur.py:77:1: F401 'numba.prange' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/opt_tax_recur.py:77:1: F401 'numba.float64' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/opt_tax_recur.py:78:1: F401 'numba.experimental.jitclass' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/permanent_income_dles.py:57:1: F401 'quantecon as qe' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/permanent_income_dles.py:59:1: F401 'scipy.linalg as la' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/rosen_schooling_model.py:46:1: F401 'quantecon.LQ' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/rosen_schooling_model.py:49:1: F401 'math.sqrt' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/smoothing_tax.py:100:1: F401 'scipy.linalg as la' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/un_insure.py:500:1: F401 'scipy.optimize' imported but unused
/Users/thebigbool/repos/lecture-python-advanced.myst/__test_code_quality_tmp/un_insure.py:502:1: F401 'scipy.interpolate.interp1d' imported but unused
```

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #139 

This PR:
1. removes unused imports
2. removes extra white space

### CODE REVIEW

**Comment by jstac** [comment]
Many thanks @Smit-create .  I will leave this one for @mmcky , who is on holidays but will be back soon.

**Comment by mmcky** [comment]
@Smit-create is this still relevant. Let me know and I can review + merge. Thanks.

**Comment by mmcky** [comment]
@Smit-create do you know what this RED text means in a GitHub diff? I haven't seen this before

Screenshot 2023-12-19 at 5 18 28 pm

**Comment by Smit-create** [comment]
Thanks @mmcky. Sorry for the delayed response. This color is rarely seen but I read somewhere that it denotes a syntax error. I am not sure how that is coming up in a `.md` file.

**Comment by Smit-create** [comment]
This is the fix: https://github.com/QuantEcon/lecture-python-advanced.myst/pull/142/commits/d42007d3eeaf448f4f3077e3e7df46891e2c0f7c that removes the dark red background. GitHub probably thought it was a syntax error in `md` format.

**Comment by mmcky** [comment]
thanks @Smit-create

**Comment by mmcky** [comment]
@Smit-create I am seeing two execution failures on the preview build that is not on the current live site

https://6581b2a87b7a6f228f93f7a7--wonderful-lalande-528d1c.netlify.app/status

- [ ] [amss](https://6581b2a87b7a6f228f93f7a7--wonderful-lalande-528d1c.netlify.app/amss)

```
NameError: name 'float64' is not defined
```

- [ ] [opt_tax_recur](https://6581b2a87b7a6f228f93f7a7--wonderful-lalande-528d1c.netlify.app/opt_tax_recur)

```
NameError: name 'njit' is not defined
```

**Comment by Smit-create** [comment]
I see those are the missing cases as the snippet is loaded from `_static`. I'll try to fix them.

Just wanted to check that why the CI didn't fail on this?

**Comment by mmcky** [comment]
> I see those are the missing cases as the snippet is loaded from `_static`. I'll try to fix them.
> 
> Just wanted to check that why the CI didn't fail on this?

The `-n -W --keep-going` is missing from `ci.yml` is why. 🤔

**Comment by mmcky** [comment]
@Smit-create any luck on fixing the final two issues?

**Comment by Smit-create** [comment]
Sure, fixing them.

**Review by mmcky — APPROVED** [review]
thanks @Smit-create

**Pull request merged**
