### PR TITLE
[arellano] Simplify probability computations

### PR DESCRIPTION
**Pull request by TaichiSakaguchi**
Simplify probability computations.

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @TaichiSakaguchi .  I'll run the workflow and we'll get back to you.

**Comment by mmcky** [comment]
@jstac a preview build is available here

https://657a595a6af2be36a2b7a463--wonderful-lalande-528d1c.netlify.app/arellano.html

in #153

**Comment by mmcky** [comment]
thanks @TaichiSakaguchi this looks more concise. 

@jstac the plots look the same between the current `live` site and the preview build. 

From my perspective I am not sure if this improves the readability of the code as it is combining two operations into a single line. I am usually in favour of more lines as I find it typically a bit "easier" to understand (as a reader).

**Comment by oyamad** [comment]
If one wants to write it with two lines:

```py
default_states = v_c[B_idx, :] < v_d
delta = P[y_idx, default_states].sum()
```

But this looks redundant to me...

**Comment by jstac** [comment]
Thanks @TaichiSakaguchi

**Pull request merged**
