### PR TITLE
ENH: Enable Execution, GitHub Actions, update config.yml

### PR DESCRIPTION
**Pull request by mmcky**
This PR:

1. updates `literalinclude` to use `code-cell` to load code in from a file
2. configures `.github/workflows` to harmonise to `quantecon` github action workflows
3. updates `_config.yml`
4. enables `status` page for monitoring of execution times and results

### CODE REVIEW

**Comment by mmcky** [comment]
I have now updated `:file:` to `:load:`. @shlff once build is complete do you mind rechecking #15.

Thanks

**Comment by mmcky** [comment]
@AakashGfude on the latest build it looks like the `theme` is missing those components (sidebar, and buttons).

**Comment by mmcky** [comment]
@AakashGfude the latest release of `quantecon-book-theme` contained the fixes for math. So I am not sure why this test build is showing the inline math colliding more than the current live site:

The sentence below this section title demonstrates the issue. 

https://607ceb2f1d8fad05445fac10--nostalgic-wright-5fa355.netlify.app/linear_algebra.html#id7

VS

https://python.quantecon.org/linear_algebra.html#id7

Any ideas?

**Comment by AakashGfude** [comment]
@mmcky @DrDrij  seems like the math fix itself is actually causing the issue https://github.com/QuantEcon/quantecon-book-theme/pull/96/files. When I remove the css styling here https://607ceb2f1d8fad05445fac10--nostalgic-wright-5fa355.netlify.app/linear_algebra.html#vectors in safari, the "or" does not overlap.

Maybe we need to do a more holistic test, before deciding on a fix.

**Comment by mmcky** [comment]
> @mmcky @DrDrij seems like the math fix itself is actually causing the issue https://github.com/QuantEcon/quantecon-book-theme/pull/96/files. When I remove the css styling here https://607ceb2f1d8fad05445fac10--nostalgic-wright-5fa355.netlify.app/linear_algebra.html#vectors in safari, the "or" does not overlap.
> 
> Maybe we need to do a more holistic test, before deciding on a fix.

@AakashGfude is this comment in relation to:
1. `quantecon` theme not loading with all of its elements, or
2. `inline math` overlapping the adjacent text

**Comment by AakashGfude** [comment]
> @AakashGfude is this comment in relation to:
> 
> 1. `quantecon` theme not loading with all of its elements, or
> 2. `inline math` overlapping the adjacent text

Ohh sorry, for not clarifying. The comment relates to `inline math` overlapping the adjacent text.

**Comment by mmcky** [comment]
Ok I now understand why I am confused. This discussion doesn't belong here. I will move it to: https://github.com/QuantEcon/lecture-python.myst/pull/132

**Comment by AakashGfude** [comment]
@mmcky ok, so now this comment is regarding the `quantecon` theme not loading all its elements issue 😅
the following code in black_litterman.md is breaking it :

```
```{code-cell} python3
def black_litterman(λ, μ1, μ2, Σ1, Σ2):
    """
    This function calculates the Black-Litterman mixture
    mean excess return and covariance matrix
    """
    Σ1_inv = np.linalg.inv(Σ1)
    Σ2_inv = np.linalg.inv(Σ2)

    μ_tilde = np.linalg.solve(Σ1_inv + λ * Σ2_inv,
                              Σ1_inv @ μ1 + λ * Σ2_inv @ μ2)
    return μ_tilde

τ = 1
μ_tilde = black_litterman(1, μ_m, μ_est, Σ_est, τ * Σ_est)

# The Black-Litterman recommendation for the portfolio weights
w_tilde = np.linalg.solve(δ * Σ_est, μ_tilde)

τ_slider = FloatSlider(min=0.05, max=10, step=0.5, value=τ)

@interact(τ=τ_slider)
def BL_plot(τ):
    μ_tilde = black_litterman(1, μ_m, μ_est, Σ_est, τ * Σ_est)
    w_tilde = np.linalg.solve(δ * Σ_est, μ_tilde)

    fig, ax = plt.subplots(1, 2, figsize=(16, 6))
    ax[0].plot(np.arange(N)+1, μ_est, 'o', c='k',
               label=r'$\hat{\mu}$ (subj view)')
    ax[0].plot(np.arange(N)+1, μ_m, 'o', c='r',
               label=r'$\mu_{BL}$ (market)')
    ax[0].plot(np.arange(N)+1, μ_tilde, 'o', c='y',
               label=r'$\tilde{\mu}$ (mixture)')
    ax[0].vlines(np.arange(N)+1, μ_m, μ_est, lw=1)
    ax[0].axhline(0, c='k', ls='--')
    ax[0].set(xlim=(0, N+1), xlabel='Assets',
              title=r'Relationship between $\hat{\mu}$, $\mu_{BL}$, and  $ \tilde{\mu}$')
    ax[0].xaxis.set_ticks(np.arange(1, N+1, 1))
    ax[0].legend(numpoints=1)

    ax[1].set_title('Black-Litterman portfolio weight recommendation')
    ax[1].plot(np.arange(N)+1, w, 'o', c='k', label=r'$w$ (mean-variance)')
    ax[1].plot(np.arange(N)+1, w_m, 'o', c='r', label=r'$w_{m}$ (market, BL)')
    ax[1].plot(np.arange(N)+1, w_tilde, 'o', c='y',
               label=r'$\tilde{w}$ (mixture)')
    ax[1].vlines(np.arange(N)+1, 0, w, lw=1)
    ax[1].vlines(np.arange(N)+1, 0, w_m, lw=1)
    ax[1].axhline(0, c='k')
    ax[1].axhline(-1, c='k', ls='--')
    ax[1].axhline(1, c='k', ls='--')
    ax[1].set(xlim=(0, N+1), xlabel='Assets',
              title='Black-Litterman portfolio weight recommendation')
    ax[1].xaxis.set_ticks(np.arange(1, N+1, 1))
    ax[1].legend(numpoints=1)
    plt.show()
```

````

Why is it doing it is still a mystery.

**Comment by mmcky** [comment]
> Why is it doing it is still a mystery.

It is really odd that `arbitrary` code that is breaking is impacting the theme. I can't see the link here.

**Comment by mmcky** [comment]
So the lectures `black_litterman` and `matsuyama` include `interact` objects which generate interactive `ipywidget` objects. These widgets are currently injecting `javascript` that has failed to load so prevents the whole site from rendering properly. 

PR #32 addresses this by sanitising the output from cells that include `ipywidget` objects

**Comment by mmcky** [comment]
@AakashGfude so I tried switching the `remove-output` on for the interact `code-cells` but it looks like the widgets may be added at the end of the document -- so this may not be the solution to this problem. 

This is still located in the `html`:


```
{"state": {"118488c9eb054569a26fa6000651f95b": {"model_module": "@jupyter-widgets/base", "model_module_version": "1.2.0", "model_name": "LayoutModel", "state": {"_model_module": "@jupyter-widgets/base", "_model_module_version": "1.2.0", "_model_name": "LayoutModel", "_view_count": null, "_view_module": "@jupyter-widgets/base", "_view_module_version": "1.2.0", "_view_name": "LayoutView", "align_content": null, "align_items": null, "align_self": null, "border": null, "bottom": null, "display": null, "flex": null, "flex_flow": null, "grid_area": null, "grid_auto_columns": null, "grid_auto_flow": null, "grid_auto_rows": null, "grid_column": null, "grid_gap": null, "grid_row": null, "grid_template_areas": null, "grid_template_columns": null, "grid_template_rows": null, "height": null, "justify_content": null, "justify_items": null, "left": null, "margin": null, "max_height": null, "max_width": null, "min_height": null, "min_width": null, "object_fit": null, "object_position": null, "order": null, "overflow": null, "overflow_x": null, "overflow_y": null, "padding": null, "right": null, "top": null, "visibility": null, "width": null}}, "1a6c20a321ae4024aa9810da2b53c2ab": {"model_module": "@jupyter-widgets/controls", "model_module_version": "1.5.0", "model_name": "IntSliderModel", "state": {"_dom_classes": [], "_model_module": "@jupyter-widgets/controls", "_model_module_version": "1.5.0", "_model_name": "IntSliderModel", "_view_count": null, "_view_module": "@jupyter-widgets/controls", "_view_module_version": "1.5.0", "_view_name": "IntSliderView", "continuous_update": true, "description": "npts", "description_tooltip": null, "disabled": false, "layout": "IPY_MODEL_3ff4eb7361f447ec81bcb7f294c17e7e", "max": 750, "min": 25, "orientation": "horizontal", "readout": true, "readout_format": "d", "step": 25, "style": "IPY_MODEL_25e91b5bcf364c4590ef2f48515f7e06", "value": 250}}, "25e91b5bcf364c4590ef2f48515f7e06": {"model_module": "@jupyter-widgets/controls", "model_module_version": "1.5.0", "model_name": "SliderStyleModel", "state": {"_model_module": "@jupyter-widgets/controls", "_model_module_version": "1.5.0", "_model_name": "SliderStyleModel", "_view_count": null, "_view_module": "@jupyter-widgets/base", "_view_module_version": "1.2.0", "_view_name": "StyleView", "description_width": "", "handle_color": null}}, "3ff4eb7361f447ec81bcb7f294c17e7e": {"model_module": "@jupyter-widgets/base", "model_module_version": "1.2.0", "model_name": "LayoutModel", "state": {"_model_module": "@jupyter-widgets/base", "_model_module_version": "1.2.0", "_model_name": "LayoutModel", "_view_count": null, "_view_module": "@jupyter-widgets/base", "_view_module_version": "1.2.0", "_view_name": "LayoutView", "align_content": null, "align_items": null, "align_self": null, "border": null, "bottom": null, "display": null, "flex": null, "flex_flow": null, "grid_area": null, "grid_auto_columns": null, "grid_auto_flow": null, "grid_auto_rows": null, "grid_column": null, "grid_gap": null, "grid_row": null, "grid_template_areas": null, "grid_template_columns": null, "grid_template_rows": null, "height": null, "justify_content": null, "justify_items": null, "left": null, "margin": null, "max_height": null, "max_width": null, "min_height": null, "min_width": null, "object_fit": null, "object_position": null, "order": null, "overflow": null, "overflow_x": null, "overflow_y": null, "padding": null, "right": null, "top": null, "visibility": null, "width": null}}, "403d5a4e81f648a8a9f47ed7b6d9f083": {"model_module": "@jupyter-widgets/base", "model_module_version": "1.2.0", "model_name": "LayoutModel", "state": {"_model_module": "@jupyter-widgets/base", "_model_module_version": "1.2.0", "_model_name": "LayoutModel", "_view_count": null, "_view_module": "@jupyter-widgets/base", "_view_module_version": "1.2.0", "_view_name": "LayoutView", "align_content": null, "align_items": null, "align_self": null, "border": null, "bottom": null, "display": null, "flex": null, "flex_flow": null, "grid_area": null, "grid_auto_columns": null, "grid_auto_flow": null, "grid_auto_rows": null, "grid_column": null, "grid_gap": null, "grid_row": null, "grid_template_areas": null, "grid_template_columns": null, "grid_template_rows": null, "height": null, "justify_content": null, "justify_items": null, "left": null, "margin": null, "max_height": null, "max_width": null, "min_height": null, "min_width": null, "object_fit": null, "object_position": null, "order": null, "overflow": null, "overflow_x": null, "overflow_y": null, "padding": null, "right": null, "top": null, "visibility": null, "width": null}}, "47f76fab1ea54524836a53e55953e1e7": {"model_module": "@jupyter-widgets/controls", "model_module_version": "1.5.0", "model_name": "SliderStyleModel", "state": {"_model_module": "@jupyter-widgets/controls", "_model_module_version": "1.5.0", "_model_name": "SliderStyleModel", "_view_count": null, "_view_module": "@jupyter-widgets/base", "_view_module_version": "1.2.0", "_view_name": "StyleView", "description_width": "", "handle_color": null}}, "7455ae7c4feb4be7addc82a3a4fda227": {"model_module": "@jupyter-widgets/controls", "model_module_version": "1.5.0", "model_name": "FloatSliderModel", "state": {"_dom_classes": [], "_model_module": "@jupyter-widgets/controls", "_model_module_version": "1.5.0", "_model_name": "FloatSliderModel", "_view_count": null, "_view_module": "@jupyter-widgets/controls", "_view_module_version": "1.5.0", "_view_name": "FloatSliderView", "continuous_update": true, "description": "\u03c1", "description_tooltip": null, "disabled": false, "layout": "IPY_MODEL_118488c9eb054569a26fa6000651f95b", "max": 1.0, "min": 0.0, "orientation": "horizontal", "readout": true, "readout_format": ".2f", "step": 0.05, "style": "IPY_MODEL_9abf049c496c4105b2a54cb80d8f2ef3", "value": 0.2}}, "90602918ddac4c5baee0797303cece02": {"model_module": "@jupyter-widgets/base", "model_module_version": "1.2.0", "model_name": "LayoutModel", "state": {"_model_module": "@jupyter-widgets/base", "_model_module_version": "1.2.0", "_model_name": "LayoutModel", "_view_count": null, "_view_module": "@jupyter-widgets/base", "_view_module_version": "1.2.0", "_view_name": "LayoutView", "align_content": null, "align_items": null, "align_self": null, "border": null, "bottom": null, "display": null, "flex": null, "flex_flow": null, "grid_area": null, "grid_auto_columns": null, "grid_auto_flow": null, "grid_auto_rows": null, "grid_column": null, "grid_gap": null, "grid_row": null, "grid_template_areas": null, "grid_template_columns": null, "grid_template_rows": null, "height": null, "justify_content": null, "justify_items": null, "left": null, "margin": null, "max_height": null, "max_width": null, "min_height": null, "min_width": null, "object_fit": null, "object_position": null, "order": null, "overflow": null, "overflow_x": null, "overflow_y": null, "padding": null, "right": null, "top": null, "visibility": null, "width": null}}, "944bbadcdefe4ca8af9f595d37221c46": {"model_module": "@jupyter-widgets/output", "model_module_version": "1.0.0", "model_name": "OutputModel", "state": {"_dom_classes": [], "_model_module": "@jupyter-widgets/output", "_model_module_version": "1.0.0", "_model_name": "OutputModel", "_view_count": null, "_view_module": "@jupyter-widgets/output", "_view_module_version": "1.0.0", "_view_name": "OutputView", "layout": "IPY_MODEL_a00d6e6333fc4f0cbdd782c632c8d489", "msg_id": "", "outputs": [{"name": "stderr", "output_type": "stream", "text": "<ipython-input-6-c41dfacedf36>:13: MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.\n  cf = ax.pcolormesh(unitrange, unitrange, ab, cmap=\"viridis\")\n"}, {"data": {"image/png": "iVBORw0KGgoAAAANSUhEUgAAAzMAAAJDCAYAAAA//krDAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8vihELAAAACXBIWXMAAAsTAAALEwEAmpwYAAEAAElEQVR4nOz9aZRk2VUmiO7rNpu5uZnPs4fHnBEZGTlJKaUSDSDUEqjUwCtUTI9i0IPSErymBSwoWBT1uqimKIqh6cWj9UQVBVVNUYwNpQZEIYGmlFCmUqmcIjJjDg+fRzM3t8ltuO/Hufvu78Y95u6Rk7tH7m+tWHH8mt35nHOvfd/e33Zc1yWFQqFQKBQKhUKhOGzo2u8DUCgUCoVCoVAoFIqXA/0xo1AoFAqFQqFQKA4l9MeMQqFQKBQKhUKhOJTQHzMKhUKhUCgUCoXiUEJ/zCgUCoVCoVAoFIpDCf0xo1AoFAqFQqFQKA4ldv0x4zjO7ziOs+w4zvMdPnccx/nfHce54jjOs47jPPTqH6ZCoVAoFAqFQqFQBLEXZeZ3ieh9O3z+TUR00vv3w0T0f7zyw1IoFAqFQqFQKBSKnbHrjxnXdT9HROs7fOVbiOg/uQb/QER5x3FGX60DVCgUCoVCoVAoFAobXo2cmXEiugV/z3rLFAqFQqFQKBQKheI1Q/RV2IZjWeZav+g4P0wmFI0iydjDmalearmyeqstv63aLdOORlv+sq4u2Wy7Les1mxEiIorFmv6yiBM+BNxXsxWB7bbDJwDfbXvHFYftO3CKzbbZVrRLjjVwLrCtZNRsow77j8H+t73l8YhsC69wd6RORESj0VromF9vXKn3EBFRHM4bse1dl5Yr1yKG18hbjtcKr2G1mvDbieQ2ERG5cDHwHrS9bUXgWnbB511ef8A+gH2EPz8S27KeyyvFQjPpt9c2skRE5KShb8OxxLx7X63H/WXxuPQ9Pq+99OeWNzZs65tt8D2QbUUjsn7TG4c4Hhw4Vr7eDvRRXgcRg/6MEwaOUu4HPJ6JguOf7z2OfZwT+Fjw/LZxnHnHUK/KdU2ktmVbDo5pcywJOG4cs3y+uM7JRJH2E6stmc7rbsxv8z2utmRZ1JF77N72vds/r3vbxbHZdsNjtt6U/eP9xmvE+9iuybEk4R7wXIn9DeeMatOsl47JOo223Beei3DOxXESDYz5cN/FOWUqVqbDjMWWzJ+bDTP/JCIyD2y35X41vDGLzx28BziO+DuOZbwQyVyEc3EU2vxdnMvxHrv+//J5A/bPX8D9d7qH/pxRgfkxMO96cwZui8JoE76nQHvbO9c4PHdg7PBxBd4nsG825bo5EXMMkcD64WeU7fgQbqAt3+ZjCOwf5urAvnhe77Bd/sR18XPcl9fA54rlXc6xvyr6W8I5qVWS/hrJ4rteO3R8+E4RuVL32yXaWHVdd9C6U8WhxqvxY2aWiCbh7wkimrd90XXdjxPRx4mIcqeH3bd+/Luo3JAXi2Il5bdLRdMeHNj0l2Xi8gArb8t6K0s5s+OJNfkuPOz8dWBfSxs9fjubCf8wqG3LpamWzUPhyIhsHyfq1XKGiIgGMvLw26zJy2sZXkrPDC0TEdH1Qp+/bDAjL9DzRXMuYzl5McIXi7f1XyMiop/pvxQ65tcb33L5vURENJnZsH5+q9xLRERbcN1H0iW/Xdg293ijmvaXDablWjx34YjfPnl6joiCD018QJbq5nr3pir+siQ8uLuj9cA+iYjy8arfTkUaRET0sYkvWc/lleLfrJ3y2//5j95NRERdD8o9ziSkv45lTZ9/5poMq+nxFb+d8H4QY39eLmb9dndKJu/1ZbN8ejK8PhHRpnfdtmry4tMP/Xi51E1ERI0GvKjCj/q+bnO9sY+ueeMBMZSV+257sSGSMbOyKmMTxz+/UOGPvBRct95UNXR+PJ7wGK69IMLxsXvn/HY3zBlrNdMnj2Slb98s9co5eOeL88wnTn2S9hO/uznkty/VRvz2pvdD+vkNif7tT8o44XuA4zSfkDmR5yqcp3i8EcmYvbbe7y/D+QvHYXHbrDdz…
```

**Comment by mmcky** [comment]
@AakashGfude I have updated the `code-cell` that include `interact` and it looks like `quantecon-book-theme==0.1.7` is still broken for the advanced lectures. I suspect the `interact` objects while sanitising the `code-cell` outputs is injecting some `javascript` code somewhere.

**Comment by AakashGfude** [comment]
> @AakashGfude I have updated the `code-cell` that include `interact` and it looks like `quantecon-book-theme==0.1.7` is still broken for the advanced lectures. I suspect the `interact` objects while sanitising the `code-cell` outputs is injecting some `javascript` code somewhere.

@mmcky the refactor branch has the fix for interact, https://github.com/QuantEcon/quantecon-book-theme/pull/115 , it needs a bit of work to support icons, and tippy js though.

**Comment by mmcky** [comment]
thanks @AakashGfude what timeline do you think is realistic for QuantEcon/quantecon-book-theme#115

**Comment by AakashGfude** [comment]
> thanks @AakashGfude what timeline do you think is realistic for [QuantEcon/quantecon-book-theme#115](https://github.com/QuantEcon/quantecon-book-theme/pull/115)

I think by tomorrow, it should be ready.

**Comment by mmcky** [comment]
@AakashGfude I have update this branch to install from `master` to test upcoming `quantecon-book-theme=0.2.0`

**Comment by mmcky** [comment]
Currently `output_scroll` is used but what we really want is `input_scroll`

I will merge this PR now to bring in execution and loading code from files support and once input-scroll is supported we can change the tags

https://github.com/QuantEcon/lecture-python-advanced.myst/issues/42

**Pull request merged**
