### PR TITLE
Use vectorization and numba jitting for optimization

### LINKED ISSUE #183: Long Run Time on Lecture causing build cache issues
@kp992 this lecture

https://python-advanced.quantecon.org/black_litterman.html

is taking a very long time to run. 

I suspect this is worse than in the past. 

Would you have time to review this lecture to see if we can compute it under 3000minutes?

### PR DESCRIPTION
**Pull request by kp992**
This PR optimizes the runtime of black_litterman lecture by using vectorization and numba jitting.

Fixes #183

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @kp992 , this code looks much nicer.  @mmcky could you please check the outputs?

**Comment by kp992** [comment]
I see that the build time is too high still. Locally its working fast for me. May be some issues with the ipywidgets? The slider is not working https://python-advanced.quantecon.org/black_litterman.html. See the SS

Screenshot 2024-11-23 at 1 27 38 PM

**Comment by kp992** [comment]
The slider is working locally for me but it doesn't on live pages because the html pages are static in nature.

**Comment by kp992** [comment]
I think the high timing issue is not consistent in this lecture. I added a debug commit https://github.com/QuantEcon/lecture-python-advanced.myst/commit/a9c061fc6284ae52f409443c64b7a942dc9c1f46#commitcomment-149458134 and it just took 42s (https://674294b5a50f0309d83896e3--wonderful-lalande-528d1c.netlify.app/status).
After reverting the same commit, its ~7200s (https://6742b3a5c174582b302b578c--wonderful-lalande-528d1c.netlify.app/status).

This looks strange to me.

**Comment by mmcky** [comment]
thanks @kp992. 

We should remove the sliders as they won't work on the static site representation. Perhaps we can put the slider version in a collapsed code-block (and tag no-execute) and add a note block that says if you are running this lecture locally you can adjust the parameters using the piython slider.

**Comment by mmcky** [comment]
@kp992 I have just noticed that `matsuyama` also has a very long run time of 7000s. It may be worth checking if they both have something similar (like the widgets) that is hanging the execution? 

<head></head>
matsuyama | 2024-11-04 08:33 | cache | 7206.91 | ✅
-- | -- | -- | -- | --


[matsuyama](https://python-advanced.quantecon.org/matsuyama.html)
2024-11-04 08:33
cache
7206.91
✅

**Comment by kp992** [comment]
Thanks @mmcky. Yes, I also believe that `ipywidgets` is the one hanging the build.

**Review by mmcky — APPROVED** [review]
thanks @kp992 this is looking great.

**Pull request merged**
