### PR TITLE
Update `calvo` lecture with new visualizations and updated content

### PR DESCRIPTION
**Pull request by HumphreyYang**
This PR updates `calvo.md` by incorporating new calculations and visualizations.

### CODE REVIEW

**Comment by HumphreyYang** [comment]
Hi @mmcky, 

Apologize for presenting a huge PR to you. Tom and I are working on this and would like to show the live version to our friends and implement an extension. 

Could you please kindly review this PR and merge this if it looks good? We will come back again in one week to improve it for another round. 

Thanks so much in advance!

**Comment by mmcky** [comment]
@HumphreyYang there are a few blockers to publishing this today.

- [ ] #163 
- [ ] anaconda is not installing on any GitHub action today and we are waiting for a fix. 

You could build this lecture locally and perhaps server a rendered view of it as a GitHub gist?

**Comment by HumphreyYang** [comment]
> @HumphreyYang there are a few blockers to publishing this today.

Thanks so much for fixing these @mmcky. I have shared one of the previous previews.

**Comment by kp992** [comment]
Build error is resolved for now and so we are unblocked on this PR.

**Comment by mmcky** [comment]
thanks @HumphreyYang and @kp992. 

@HumphreyYang merging this now (as requested).

**Pull request merged**
