### PR TITLE
[coase] center inserted figures

### LINKED ISSUE #52: [lecture review] inserted figures uncentered
Hi @mmcky , I find that inserted figures are not centered.

e.g., (left: RST; right: MYST):
Screen Shot 2021-05-29 at 8 00 35 pm

Screen Shot 2021-06-03 at 11 25 01 am

Screen Shot 2021-06-03 at 11 25 28 am

### PR DESCRIPTION
**Pull request by shlff**
Hi @mmcky , this PR fix #52 .

### CODE REVIEW

**Comment by shlff** [comment]
Hi @mmcky , I find adding ``:align: center`` to the inserted is not working--inserted figures are not centralized.

Please see the following screenshot from the preview:
Screen Shot 2021-06-18 at 12 16 05 pm

**Comment by mmcky** [comment]
@DrDrij @AakashGfude the generated `html` looks like it is surrounded by a `div`

```html
<div class="figure align-center">
<img alt="_images/subcontracting.png" src="_images/subcontracting.png">
</div>
```

do we have missing styles for centering figures. That may need to be an upstream fix?

**Comment by mmcky** [comment]
A new `quantecon-book-theme=0.2.5` is now released

**Comment by mmcky** [comment]
thanks @shlff and @AakashGfude

**Pull request merged**
